databaseChangeLog:
  - changeSet:
      id: 1
      author: YarikRevich
      changes:
        - createTable:
            tableName: config
            columns:
              - column:
                  name: id
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR
                  constraints:
                    unique: true
                    nullable: false
              - column:
                  name: hash
                  type: VARCHAR
                  constraints:
                    nullable: false
        - createTable:
            tableName: secret
            columns:
              - column:
                  name: id
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: session
                  type: INT
                  constraints:
                    nullable: false
              - column:
                  name: credentials
                  type: VARCHAR
                  constraints:
                    nullable: true
        - createTable:
            tableName: provider
            columns:
              - column:
                  name: id
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR
                  constraints:
                    unique: true
                    nullable: false
        - createTable:
            tableName: exporter
            columns:
              - column:
                  name: id
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: host
                  type: VARCHAR
                  constraints:
                    unique: true
                    nullable: false
        - createTable:
            tableName: content
            columns:
              - column:
                  name: id
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: location
                  type: VARCHAR
                  constraints:
                    nullable: false
              - column:
                  name: additional
                  type: BOOLEAN
                  constraints:
                    nullable: false
              - column:
                  name: provider
                  type: INT
                  constraints:
                    foreignKeyName: provider_fk
                    references: provider(id)
                    nullable: false
                    deleteCascade: true
              - column:
                  name: exporter
                  type: INT
                  constraints:
                    foreignKeyName: exporter_fk
                    references: exporter(id)
                    nullable: true
                    deleteCascade: true
              - column:
                  name: secret
                  type: INT
                  constraints:
                    foreignKeyName: secret_fk
                    references: secret(id)
                    nullable: false
                    deleteCascade: true
        - loadData:
            tableName: provider
            usePreparedStatements: false
            separator: ;
            relativeToChangelogFile: true
            file: data/data.csv
            encoding: UTF-8
            quotchar: ''''
            columns:
              - column:
                  header: Name
                  name: name
                  type: STRING