global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 15s

    static_configs:
      - targets: ['${repoachiever-diagnostics-prometheus.host}']

  - job_name: 'node-exporter'

    scrape_interval: 15s

    static_configs:
      - targets: ['${repoachiever-diagnostics-prometheus-node-exporter.host}']
