# Represents section used to declare desired content.
content:
  # Represents locations of VCS provider repositories, which are intended to be used for requested operations.
  locations:
    - name: "[YarikRevich]test:master" # Represents location definition name.

      # Enables additional content download of repositories of VCS provider repositories.
      additional: true
    - name: "[YarikRevich]scripts:master" # Represents location definition name.

      # Enables additional content download of repositories of VCS provider repositories.
      additional: true
    - name: "[YarikRevich]odb:master" # Represents location definition name.

      # Enables additional content download of repositories of VCS provider repositories.
      additional: true
    - name: "[YarikRevich]tetris:main" # Represents location definition name.

      # Enables additional content download of repositories of VCS provider repositories.
      additional: true
    - name: "[YarikRevich]tmpm:master" # Represents location definition name.

      # Enables additional content download of repositories of VCS provider repositories.
      additional: true
    - name: "[YarikRevich]portfolio:master" # Represents location definition name.

      # Enables additional content download of repositories of VCS provider repositories.
      additional: true
    - name: "[YarikRevich]ai-commit-generator:master" # Represents location definition name.

      # Enables additional content download of repositories of VCS provider repositories.
      additional: true
    - name: "[YarikRevich]website:main" # Represents location definition name.

      # Enables additional content download of repositories of VCS provider repositories.
      additional: true
    - name: "[YarikRevich]vim-config:master" # Represents location definition name.

      # Enables additional content download of repositories of VCS provider repositories.
      additional: true
    - name: "[YarikRevich]critical_db_framework:master" # Represents location definition name.

      # Enables additional content download of repositories of VCS provider repositories.
      additional: true

# Represents section used for VCS provider configuration.
service:
  # Represents the selected VCS provider for RepoAchiever. The first part divided by the hyphen represents
  # selected VCS core type and the second part defines external provider.
  #
  # Supported providers are "exporter" and "git-github".
  provider: "git-github"

  # Represents section used for RepoAchiever Exporter configuration.
  exporter:
    # Represents address for the host of RepoAchiever Exporter.
    host: "http://localhost:10000"

  # Represents credentials used for the selected VCS provider. Can be left null, if the provider does not
  # require it.
  credentials:
    # Represents session identificator, used to distinguish different workspaces and thus separate content inside.
    id: "1"

    # Represents authentication token intended to be used for VCS provider API access permission.
    token: ""

# Represents section used for RepoAchiever API Server configuration.
api-server:
  # Represents address for the host of RepoAchiever API Server.
  host: "http://localhost:8085"